# Generated by Django 5.1.6 on 2025-02-12 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_product_inventory_product_asin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforecast',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sales_forecasts', to='crm.product'),
            preserve_default=False,
        ),
    ]
