# Generated by Django 5.1.6 on 2025-02-12 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_salesforecast_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforecast',
            name='forecast_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date for which the sales forecast applies'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='predicted_sales',
            field=models.DecimalField(decimal_places=2, help_text='Predicted sales figure', max_digits=12),
        ),
    ]
